### ISSUE TITLE
Bug in Mistral prompt template

### ISSUE THREAD

**Issue by FelixMMueller** [zylon-ai/private-gpt#1540]
I think I have found a bug in the prompt template for the Mistral model. The current template does not include the assistant response in the message history. As this is my first time working with an open source LLM, I am not 100% sure if I am right. 

My suggestion to fix this would be:

```python
class MistralPromptStyle(AbstractPromptStyle):
    def _messages_to_prompt(self, messages: Sequence[ChatMessage]) -> str:
        prompt = "<s>"
        user_message_counter = 0
        for message in messages:
            role = message.role
            text = message.content
            
            if role == "system":
                prompt += f"[INST] {text}\n"
            elif role == "assistant":
                prompt += f"{text}</s>"
            elif role == "user":
                if user_message_counter != 0:
                    # not the first user message
                    prompt += "[INST]"
                prompt += f"{text}[/INST]"
                user_message_counter += 1
            else:
                raise ValueError(f"{role} is an invalid role")
        return prompt

    def _completion_to_prompt(self, completion: str) -> str:
            return self._messages_to_prompt(
                [ChatMessage(content=completion, role=MessageRole.USER)]
            )

```

I played a bit with this prompt template and it gave good results. With the old template, the model was not able to remember its old answers.

I refer to the instructions in this document for the "Mistral-7B-Instruct-v0.2" model: https://github.com/huggingface/chat-ui/blob/main/.env.template

**Comment by qdm12** [comment]
Sorry to jump in, I use vllm+mistral together with privategpt, and the answer I get is non-stop repeating `[INST] My question [/INST] LLM Answer`, did you encounter this as well? Could it be related to the bug you spotted?

**Comment by jaluma** [comment]
Fixed in https://github.com/zylon-ai/private-gpt/pull/1954
