### ISSUE TITLE
Increase layers offloading to GPU and GPU buffer size

### ISSUE THREAD

**Issue by thanhtantran** [zylon-ai/private-gpt#1630]
I have run successfully AMD GPU with privateGPT, now I want to use two GPU instead of one to increase the VRAM size.
```
llm_load_tensors: ggml ctx size =    0.22 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:        CPU buffer size =    84.31 MiB
llm_load_tensors:     OpenCL buffer size =  4115.46 MiB
```

How to increase the layers offloading to GPU? and will it increase the GPU buffer size?

**Comment by SuperSonnix71** [comment]
You are asking the wrong question. Running multiple GPU is totally different ballgame than increasing the layer offloading....

With that said.  I'm working on it 

https://github.com/imartinez/privateGPT/issues/1521#issuecomment-1963085662

**Comment by neofob** [comment]
@thanhtantran :
* By default, privategpt offloads all layers to GPU. In your case, all 33 layers are offloaded. You can adjust that number in the file [`llm_component.py:45`][0] 
* Running multiple GPUs will have the number of offloaded layers spreaded across multiple GPUs.
  * If your model uses 36 GB, you offload 28 layers which takes about 28GB, 2 GPUs with 16 GB each, 28/2=14 GB will be allocated on each GPU. The remaining 36-28=8GB will allocated on the system memory.
  
Hope that helps.

[0]:https://github.com/imartinez/privateGPT/blob/main/private_gpt/components/llm/llm_component.py#L45
