### ISSUE TITLE
[Feature Request] Support Ollama Embedding

### ISSUE THREAD

**Issue by huaxlin** [zylon-ai/private-gpt#1650]
## Motivation

Ollama has been supported embedding at [v0.1.26 - Support for bert and nomic-bert embedding models](https://github.com/ollama/ollama/releases/tag/v0.1.26)

I think it's will be more easier ever before when every one get start with privateGPT, without extra setup step(`python script/setup`)

## Usage[^1]
This model is an embedding model, meaning it can only be used to generate embeddings.

### REST API

```
curl http://localhost:11434/api/embeddings -d '{
  "model": "nomic-embed-text",
  "prompt": "The sky is blue because of Rayleigh scattering"
}'
```

### Python library

```
ollama.embeddings(model='nomic-embed-text', prompt='The sky is blue because of rayleigh scattering')
```

[^1]: https://ollama.com/library/nomic-embed-text#Usage

**Comment by Robinsane** [comment]
This can be closed, using Ollama embeddings in my own project as we speak :)

**Comment by huaxlin** [comment]
supported ollama embedding, refer to settings-ollama.yaml
