### ISSUE TITLE
'Requested tokens () exceed context window of 3900' Issue

### ISSUE THREAD

**Issue by mthomati** [zylon-ai/private-gpt#1667]
Hi, when using bigger files (JSON or YAML structured files), I am unable to send queries and ask questions against my data.

Nothing returns back.  But in the console I get the following message:

`20:06:21.311 [WARNING ] llama_index.chat_engine.types - Encountered exception writing response to history: Requested tokens (9614) exceed context window of 3900 `

If I use very small files, that works, but that isn't useful to use for a local GPT with my own data.  Any help with this?  Thanks!

**Comment by felciano** [comment]
I'm seeing the same

**Comment by ScioShield** [comment]
For anyone else having this issue you can change the context window in the [settings.yaml](https://github.com/imartinez/privateGPT/blob/12f3a39e8aab94f1156adac7dcfbba29929840a9/settings.yaml#L42) file to something above what's giving you the error and reload the app. So for the above issue change `context_window: 3900` in the `llm:` section to something like `context_window: 10000` this will incur a cost of GPU performance as mentioned in [fee9f08](https://github.com/imartinez/privateGPT/commit/fee9f08ef3d9473eb4d0b35c3c6697596b8c3f7c). I don't know how large this fix scales so at some value it may not work. It worked for me with a window of `14305` on my hardware. Hope it helps

**Comment by felciano** [comment]
Thanks @ScioShield this fixed the issue for me as well.
