### ISSUE TITLE
How to speed up ingestion

### ISSUE THREAD

**Issue by jonjia** [zylon-ai/private-gpt#1713]
I'm curious about this and how to speed up.  Is it Ollama issue?
The size of my xxx.csv file is 15M. 
Ingestion costs  25 minutes.

![IMG_9537](https://github.com/imartinez/privateGPT/assets/20496707/fe524308-58f8-43ec-b5c9-d50a8800ad40)

**Comment by RolT** [comment]
If you installed Ollama recently you may want to try this: https://github.com/ollama/ollama/issues/3029#issuecomment-1987177366

**Comment by jaluma** [comment]
In the last ollama version (v.2.0), you can select how many concurrent requests and parallel you want. Please check this [article](https://www.linkedin.com/pulse/enhanced-concurrency-features-ollamas-latest-update-robyn-le-sueur-bh7rf) :)
