### ISSUE TITLE
Issues installing dependencies

### ISSUE THREAD

**Issue by life00** [zylon-ai/private-gpt#1736]
I followed the installation guide and wanted to install local ollama only setup. I cloned the repo, install poetry, and ran the command.   Afterwards it created some keyring and it seems it expects me to have KWallet? I really don't understand why would it do this? Sorry I am not a python dev, and I am not willing to install a whole KDE environment to get this working. What do I do?

```sh
$ poetry install --extras "ui llms-ollama embeddings-ollama vector-stores-qdrant"
The currently activated Python version 3.12.2 is not supported by the project (>=3.11,<3.12).
Trying to find and use a compatible version.
Using python3.11 (3.11.8)
Installing dependencies from lock file

Package operations: 140 installs, 1 update, 0 removals

  • Installing wrapt (1.16.0): Failed

  DBusException

  org.freedesktop.DBus.Error.ServiceUnknown: The name :1.181 was not provided by any .service files

  at /usr/lib64/python3.12/site-packages/dbus/connection.py:634 in call_blocking
      630│                           args, signature, e.__class__, e)
      631│             raise
      632│
      633│         # make a blocking call
    → 634│         reply_message = self.send_message_with_reply_and_block(
      635│             message, timeout)
      636│         args_list = reply_message.get_args_list(**get_args_opts)
      637│         if len(args_list) == 0:
      638│             return None

The following error occurred when trying to handle this error:


  InitError

  Failed to open keyring: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.181 was not provided by any .service files.

  at /usr/lib/python3.12/site-packages/keyring/backends/kwallet.py:100 in connected
       96│             remote_obj = bus.get_object(self.bus_name, self.object_path)
       97│             self.iface = dbus.Interface(remote_obj, 'org.kde.KWallet')
       98│             self.handle = self.iface.open(self.iface.networkWallet(), wId, self.appid)
       99│         except dbus.DBusException as e:
    → 100│             raise InitError('Failed to open keyring: %s.' % e)
      101│
      102│         if self.handle < 0:
      103│             return False
      104│         self._migrate(service)

```

**Comment by life00** [comment]
I have `gnome-keyring` installed btw. So what does it want?

**Comment by feijoes** [comment]
Are you on Linux/Windows/Mac?

**Comment by life00** [comment]
> Are you on Linux/Windows/Mac?

I am on linux

**Comment by feijoes** [comment]
@life00  I find that this is usually an issue with Python dependencies used in these files either not installed or somehow broken.

Please try the following: `sudo apt install --reinstall python3-apt python3-dbus python3-gi`

**Comment by life00** [comment]
> @life00 I find that this is usually an issue with Python dependencies used in these files either not installed or somehow broken.
>
> Please try the following: `sudo apt install --reinstall python3-apt python3-dbus python3-gi` If this does not work, create a virtual environment and install all the requirements.

@feijoes well, I don't use Debian based distribution but I use Fedora. Anyways I tried to reinstall those package with dnf and I already had all of them installed: `dnf reinstall python3-dnf python3-dbus python3-gobject` and it did not help. I even installed KWallet, but it still did not help.

Does privateGPT handle at least some credentials? Because it appears that it first creates a keyring, and then after it is created/unlocked it tries to use to to store some credentials using KWallet. But I probably have some issues with KWallet config because I do not use KDE. I guess that it has KWallet hardcoded. 

By virtual environment you mean python virtual env?
```bash
python3.11 -m venv .venv
source .venv/bin/activate
poetry install --extras "ui llms-ollama embeddings-ollama vector-stores-qdrant"
```
^ this did not help

I could try running it inside a VM but that does not seem worth it.

**Comment by life00** [comment]
I was searching online for similar error log and got a brilliant idea to search in poetry's issues. I found https://github.com/python-poetry/poetry/issues/1917#issuecomment-1235998997 which fixes the issue.

Sorry for not doing this earlier.
