### ISSUE TITLE
Geman Language doesn't run

### ISSUE THREAD

**Issue by estkae** [zylon-ai/private-gpt#1791]
PrivateGPT does not work in German. I have made several tests. It only works in English. I have tested the following models: Gemma, Mixtral. The only one that works reasonably well is Mistral with nomic-embed-text:latest.
How do I set Mixtral or Gemma?
With Ollama Mixtral speak german but with PivateGPT not. Model speak only english understand german.![Screenshot 2024-03-25 113353](https://github.com/zylon-ai/private-gpt/assets/3465491/031bd911-9dc6-44fb-bc51-342862f0d327)

**Comment by tobiasoberrauch** [comment]
You can change the system prompts https://github.com/zylon-ai/private-gpt/blob/main/settings.yaml#L25
and change the model to a german model in this line https://github.com/zylon-ai/private-gpt/blob/main/settings.yaml#L53
