### ISSUE TITLE
Error : 403 Forbidden None: cannot access content at : https://huggingface.co/BAAI/bge-small-en-v1.5. While run poetry run python scripts/scripts.py

### ISSUE THREAD

**Issue by Rastih271980** [zylon-ai/private-gpt#1793]
We are getting below error while run setup.py in poetry.
403 Forbidden None: cannot access content at : https://huggingface.co/BAAI/bge-small-en-v1.5. While run poetry run python scripts/scripts.py
Kindly help us to resolve this issue.

**Comment by qdm12** [comment]
You probably need to set your huggingface auth token somewhere.

**Comment by Rastih271980** [comment]
Thanks for your response. Can you guide us in which file or place we need to give before run this? Because we got struck in this place while in deployment.

**Comment by qdm12** [comment]
> poetry run python scripts/scripts.py

There is no scripts.py, what's the file you were running?

> Can you guide us in which file or place we need to give before run this?

Sorry I mixed it up with another program (vllm), I don't think you can set an access token for now. Maybe your machine IP address is blocked from accessing https://huggingface.co/BAAI/bge-small-en-v1.5? Because accessing it from where I am works fine 🤔

**Comment by Rastih271980** [comment]
I am running scripts.py
It was working fine in my personal laptop. But i tried the same in our office PC. I am getting this error. Suppose if any block, will i need to check in our firewall side?

**Comment by qdm12** [comment]
> I am running scripts.py

Where? There is no scripts/scripts.py, see https://github.com/zylon-ai/private-gpt/tree/main/scripts

> Suppose if any block, will i need to check in our firewall side?

No it's not your firewall, it's huggingface refusing the access ("forbidden")

**Comment by Rastih271980** [comment]
Thanks for your kind response. We asked our team to whitelist. Now it is working.

After deploy i run the application. It is deployed in 127.0.0.1:8001. I can ingested our documents. After ingested, i used search files and gave some prompt in search. It is taking nearly 120 secs to 220 secs to give the response. Our server is Windows server with 64 GB RAM but it is taking too much time to give response. Please kindly guide us how to speed the response while searching with use of our documents.

**Comment by Rastih271980** [comment]
Thanks for the update
