### ISSUE TITLE
When using Ollama as the engine for LLM, restart the llama model every time?

### ISSUE THREAD

**Issue by 17Reset** [zylon-ai/private-gpt#1803]
If you are using Ollama alone, Ollama will load the model into the GPU, and you don't have to restart loading the model every time you call Ollama's api. But in privategpt, the model has to be reloaded every time a question is asked, which greatly increases the Q&A time.

**Comment by dbzoo** [comment]
I think this solves your problem https://github.com/zylon-ai/private-gpt/pull/1800 the default is 5m.  Increase it.

```
ollama:
  keep_alive: 30m
```

**Comment by 17Reset** [comment]
Yes, this has been solved, the problem is that the Embedding's model and the LLM's model are both using the same ollama api, it would be nice to separate them. Every time a question is asked the Embedding model is called first, which breaks the LLM model in memory.
