### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by anamariaUIC** [zylon-ai/private-gpt#1817]
Hello,

I installed private GPT via:

```
rm -rf .local .cache /scratch/network/$USER/privateGPT /scratch/network/$USER/tmp
mkdir /scratch/network/$USER/tmp
export TMPDIR=/scratch/network/$USER/tmp
module load Python/3.11.3-GCCcore-12.3.0
pip install --user poetry
module load git
module load CUDA
export PATH=$PATH:/home/$USER/.local/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/$USER/.local/lib
cd /scratch/network/$USER
git clone https://github.com/imartinez/privateGPT.git
cd privateGPT/
export PYTHONPATH=$PYTHONPATH:$PWD
poetry install --extras "ui llms-llama-cpp embeddings-huggingface vector-stores-qdrant"
poetry run python scripts/setup
CMAKE_ARGS='-DLLAMA_CUBLAS=on' poetry run pip install --force-reinstall --no-cache-dir llama-cpp-python
PGPT_PROFILES=local make run
```

When I query a 3 pages long .pdf file I am getting: Segmentation fault (core dumped) error. 
Please see in attach details.

How this can be resolved?

<img width="1648" alt="Screen Shot 2024-04-01 at 4 01 33 PM" src="https://github.com/zylon-ai/private-gpt/assets/84808692/a47335fb-d5a0-483f-a8e5-31f4d19ab787">
<img width="1062" alt="Screen Shot 2024-04-01 at 4 27 15 PM" src="https://github.com/zylon-ai/private-gpt/assets/84808692/3e841f4a-21aa-467e-844f-4c95f1aa5b93">

**Comment by beaconai** [comment]
i think your GPU utilization increased

**Comment by beaconai** [comment]
i'm facing the problem "Initial token count exceed token limit" can anyone help me out, im upload a CVS file and im getting this error.

**Comment by anamariaUIC** [comment]
I only queried a tiny .txt file one question and attempted to ask a 3 page .pdf one question when I received this segmentation error…

Does privateGPT has the run on a GPU?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by boufaka** [comment]
I solve the same issue (segementation fault) changing a file in version 0.5.0:

**privateGPT/private_gpt/components/llm/llm_component.py**

The setting **"offload_kqv": True** to **"offload_kqv": False** 

I hope this helps
