### ISSUE TITLE
Can't Upload PDFs to PrivateGPT

### ISSUE THREAD

**Issue by kj4274** [zylon-ai/private-gpt#1819]
### Discussed in https://github.com/zylon-ai/private-gpt/discussions/1818

<div type='discussions-op-text'>

<sup>Originally posted by **kj4274** April  1, 2024</sup>
Hello, I am new to coding / privateGPT.

Initially, I had private GPT set up following the "Local Ollama powered setup". Under that setup, i was able to upload PDFs but of course wanted private GPT to run faster. So I switched to Llama-CPP Windows NVIDIA GPU support. Now, Private GPT can answer my questions incredibly fast in the LLM Chat mode. However, i can no longer upload PDFs, enabling Query Files. 

Whenever I try to upload a PDF, I always get ---- ValueError: could not broadcast input array from shape (384,) into shape (768,)

What can I do to make PrivateGPT accept my pdfs again? Thank you for the help.</div>

**Comment by MuhammadShifa** [comment]
The issue is resolved #1759

**Comment by kj4274** [comment]
> The issue is resolved #1759

thank you that fixed it
