### ISSUE TITLE
Question: Can I put two privateGPT projects in same dir

### ISSUE THREAD

**Issue by jonjia** [zylon-ai/private-gpt#1820]
Question: Can I put two privateGPT projects in same dir

Any conflicts or data will be the same source?

Or how do I handle this in config file?

separate ingestion and ingested documents result is the same between two projects.

How to config this

**Comment by jaluma** [comment]
What does it mean to have two privategpt projects? Two instances?
PrivateGPT allows to deploy so many instances as you need. Our recommendation is avoid to use `llama-cpp`, use a server inference (e.g. `ollama`); and a server vector database (e.g. run a qdrant server instead of local version).

**Comment by jonjia** [comment]
Yes, two instances.
Can I use two vector databases of local version. I cloned two privateGPT repo, it seems they use same vector database.
Can I config vector database two make them independent by config port or anything else

**Comment by jaluma** [comment]
If you're using qdrant local version, and two folder, it will create two `local_data` folders. Are you sure that you're running two parallel codes?

**Comment by jonjia** [comment]
Thank you very much
