### ISSUE TITLE
how to bypass the connexion to huggingface

### ISSUE THREAD

**Issue by marouahamdi** [zylon-ai/private-gpt#1849]
hello, i have dowloaded the models locally but when i do make run i have this error, the issue is the connexion to HF. can i by pass it plz?
requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))"), '(Request ID: daac27c7-b24f-4c19-a707-895d5061595f)')

**Comment by jaluma** [comment]
You're downloading mistral tokenizer. You can check more information [here](https://huggingface.co/docs/transformers/en/main_classes/tokenizer).
We're working to prevent to download or require to download more things out-of-the-box.
