### ISSUE TITLE
Add support for gpt-4-turbo in llamaindex-multi-model

### ISSUE THREAD

**Issue by Prem95** [zylon-ai/private-gpt#1853]
Current llama-index package is outdated and does not support the new gpt-4-turbo which got out of preview.

Add the dependencies in poetry or install after **`PGPT_PROFILES=openai make run`**

`poetry add llama-index-multi-modal-llms-openai`

Reference in `llama_index/llms/openai/utils.py`

```
"gpt-4": 8192,
"gpt-4-32k": 32768,
turbo models (Turbo, JSON mode)
"gpt-4-1106-preview": 128000,
"gpt-4-0125-preview": 128000,
"gpt-4-turbo-preview": 128000,
# multimodal model
"gpt-4-vision-preview": 128000,
"gpt-4-turbo-2024-04-09": 128000,
"gpt-4-turbo": 128000
```

**Comment by jaluma** [comment]
Fixed [here](https://github.com/zylon-ai/private-gpt/pull/1987)
