### ISSUE TITLE
[Request] Offline mode during installation (required for Nix packaging)

### ISSUE THREAD

**Issue by drupol** [zylon-ai/private-gpt#1870]
Hello,

I'm currently integrating `private-gpt` into Nix and creating a NixOS module as part of this [PR](https://github.com/NixOS/nixpkgs/pull/305586). I noticed that when running `private-gpt`, some requests are made to the internet (_hence the creation of the `tiktoken_cache` directory_).

NixOS builds and tests modules in a completely isolated environment, without network access or environmental variables, making it challenging to run tests effectively.

I'm opening this request to see if it would be possible to enable some kind of offline mode and avoid doing external request by default. I don't know how it could be done, but since we're relying on configuration on YAML files, maybe we could add a flag in there to disable access to the network?

There are already multiple issues open about this: https://github.com/zylon-ai/private-gpt/issues/467, https://github.com/zylon-ai/private-gpt/issues/1151, https://github.com/zylon-ai/private-gpt/issues/1179, https://github.com/zylon-ai/private-gpt/pull/1467, https://github.com/zylon-ai/private-gpt/issues/1497, https://github.com/zylon-ai/private-gpt/issues/1766, https://github.com/zylon-ai/private-gpt/issues/1861

What do you think about this idea? Could we consider including this feature in the next release? What are your thoughts?

**Comment by imartinez** [comment]
There needs to be a tokenizer downloaded, given the RAG implementation (using LLamaIndex) needs to be able to count tokens. 

LlamaIndex defaults to tokenizer https://docs.llamaindex.ai/en/stable/module_guides/models/llms/?h=tiktoken#a-note-on-tokenization

So there is no way to avoid downloading the tokenizer at some point. Think of it as any other dependency. 

I think there could be a couple options:
- Add the download of the tokenizer as part of the packaging process. 
- Add the file itself to the cache folder directly (it is less than 2MB), just like in this solution https://stackoverflow.com/a/76107077

**Comment by drupol** [comment]
That worked very well, thank you !!!
