### ISSUE TITLE
Install Whisper for Audio/Video Transcription.

### ISSUE THREAD

**Issue by minhanh1234** [zylon-ai/private-gpt#1877]
I try to upload an audio/video mp3 or mp4, but i am getting the following error:

Error
Please install OpenAI whisper model 'pip install git+https://github.com/openai/whisper.git' to use the model

I try to install Whisper:
pip install git+https://github.com/openai/whisper.git
pip install -U openai-whisper

but nothing seem to work.

Running Ubuntu 22.06 and i also try running on WSL2 (Windows)

**Comment by jaluma** [comment]
To add new dependencies, you will need to use `poetry` tool. You can check more [here](https://python-poetry.org/docs/managing-dependencies/)
