### ISSUE TITLE
Can't run the private_gpt module.

### ISSUE THREAD

**Issue by umeshKandhalu** [zylon-ai/private-gpt#1886]
I almost done everything perfectly. But once i try to run the private_gpt module t show me some errors:

"TypeError: BertModel.__init__() got an unexpected keyword argument 'safe_serialization'"

How to solve this error ?

**Comment by BBjie** [comment]
For me, just upgrade llama-index-embeddings-huggingface 
`llama-index-embeddings-huggingface 0.1.5, solved in 0.2.0`

**Comment by jaluma** [comment]
Fixed in last `main` version :)
