### ISSUE TITLE
qdrant RAM usage (?allow quantisation and memmap)

### ISSUE THREAD

**Issue by Smensink** [zylon-ai/private-gpt#1892]
hello, I am attempting to create a qdrant database with a large collection of medical guidelines. Unfortunately although the raw text is only 800MB the database rapidly grows to 15+ GB before the privateGPT instances crashes. The RAM usage goes to 40-50GB+. I am aware that qdrant supports quantisation and keeping the database on disk instead of in RAM, however I cannot seem to get it working with privateGPT (the way the vectorstore is loaded is not the same as in the qdrant documentation) is it possible to allow these features?

**Comment by Anush008** [comment]
If the collection has been created, you can update the collection to use quantization and on-disk vectors. It is documented at https://qdrant.tech/documentation/concepts/collections/#update-collection-parameters.

There's also a tutorial about loading a large amount of vectors.
https://qdrant.tech/documentation/tutorials/bulk-upload/#bulk-upload-a-large-number-of-vectors

**Comment by Smensink** [comment]
huge, thats very helpful thanks, I'll try it tomorrow. Is there any plan to include these options natively in the repo?

**Comment by Anush008** [comment]
> Is there any plan to include these options natively in the repo?

I am unsure. But it would make sense to call them externally since they're not very common operations.

**Comment by Smensink** [comment]
so i have added client.update_collection(collection_name="make_this_parameterizable_per_api_call",optimizers_config=models.OptimizersConfigDiff(indexing_threshold=0)hnsw_config=models.HnswConfigDiff(on_disk=True),quantization_config=models.ScalarQuantization(scalar=models.ScalarQuantizationConfig(type=models.ScalarType.INT8,always_ram=True,),))

prior to self.vector_store=typing.cast(VectorStore,QdrantVectorStore(client=client,collection_name="make_this_parameterizable_per_api_call",))

it runs without error however i am yet to see a difference in RAM usage. I wonder whether the way that the vector store is called automatically loads it into memory?

**Comment by Smensink** [comment]
it works!, still more ram usage than i wouldve thought, but seems to level out around 18gb

**Comment by Anush008** [comment]
I'd also recommend referring to https://qdrant.tech/documentation/guides/optimize/.
