### ISSUE TITLE
win10 : make run raise error

### ISSUE THREAD

**Issue by alexhmyang** [zylon-ai/private-gpt#1894]
win10 : make run raise error, where is wrong? 

I also add settings.yaml , but raise new error 
follow by this post: 
https://medium.com/@ingridwickstevens/chat-with-your-local-documents-privategpt-lm-studio-c6ff94d0dfe3

![image](https://github.com/zylon-ai/private-gpt/assets/10215059/f612a65e-ce38-4b29-b02e-5280030ec996)
![image](https://github.com/zylon-ai/private-gpt/assets/10215059/ab2f82f8-2aea-4e2f-bbb3-048215244fca)
![image](https://github.com/zylon-ai/private-gpt/assets/10215059/883b0896-94fb-44e8-8b21-dec5c340065e)

**Comment by jaluma** [comment]
Please, update to last changes. In last version `vllm` is working as expected :)
