### ISSUE TITLE
Security And Privacy Concerns for input data on latest release  

### ISSUE THREAD

**Issue by pankajigec26** [zylon-ai/private-gpt#1895]
in the latest release we are getting following error while installing private GPT

```
LLM model downloaded!
Downloading tokenizer mistralai/Mistral-7B-Instruct-v0.2
Traceback (most recent call last):
  File "/home/epanumk/miniconda3/envs/privategpy/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status
    response.raise_for_status()
  File "/home/epanumk/miniconda3/envs/privategpy/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json
```

In order to resolve this we need to login to hugging face and generate token .   Which was not the case earlier 
How can i make sure that my input data is still secure and is not exposed to outside.

**Comment by psychopatz** [comment]
This project is open source and you can read if it sends some of your data outside easily. As for the huggingface part, its just required when you download the models from the start just to verify if youre their costumer, this is not a scope from this app but from the huggingface itself

**Comment by jaluma** [comment]
You'll need a `HF_TOKEN` in order to download `mistral` tokenizer. Please check: https://huggingface.co/docs/hub/en/models-gated

Let's try to find a solution to avoid having to download something when it is not necessary (e.g. ollama, api, etc).
