### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by LyubomirValeriev** [zylon-ai/private-gpt#1907]
poetry run python -m private_gpt
The currently activated Python version 3.12.3 is not supported by the project (>=3.11,<3.12).
Trying to find and use a compatible version.
Using python3 (3.11.9)
23:57:54.758 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "G:\Project\private-gpt\private_gpt\__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "G:\Project\private-gpt\private_gpt\main.py", line 11, in <module>
    app = create_app(global_injector)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Project\private-gpt\private_gpt\launcher.py", line 48, in create_app
    from private_gpt.ui.ui import PrivateGptUi
  File "G:\Project\private-gpt\private_gpt\ui\ui.py", line 8, in <module>
    import gradio as gr  # type: ignore
    ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'gradio'
make: *** [Makefile:36: run] Error 1

But in the same time i have 'gradio'

PS G:\Project\private-gpt> pip list
Package                   Version
------------------------- -----------
aiofiles                  23.2.1
altair                    5.3.0
annotated-types           0.6.0
anyio                     4.3.0
attrs                     23.2.0
certifi                   2024.2.2
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
contourpy                 1.2.1
cycler                    0.12.1
dnspython                 2.6.1
email_validator           2.1.1
fastapi                   0.111.0
fastapi-cli               0.0.2
ffmpy                     0.3.2
filelock                  3.14.0
fonttools                 4.51.0
fsspec                    2024.3.1
gradio                    4.29.0
gradio_client             0.16.1
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.0
idna                      3.7
importlib_resources       6.4.0
Jinja2                    3.1.3
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.8.4
mdurl                     0.1.2
numpy                     1.26.4
orjson                    3.10.3
packaging                 24.0
pandas                    2.2.2
pillow                    10.3.0
pip                       24.0
pydantic                  2.7.1
pydantic_core             2.18.2
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.35.1
requests                  2.31.0
rich                      13.7.1
rpds-py                   0.18.0
ruff                      0.4.3
semantic-version          2.10.0
setuptools                65.5.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
starlette                 0.37.2
tomlkit                   0.12.0
toolz                     0.12.1
tqdm                      4.66.4
typer                     0.12.3
typing_extensions         4.11.0
tzdata                    2024.1
ujson                     5.9.0
urllib3                   2.2.1
uvicorn                   0.29.0
watchfiles                0.21.0
websockets                11.0.3

**Comment by JeongCheolPark** [comment]
@LyubomirValeriev i have same problem. did you solve it?

**Comment by jaluma** [comment]
Please install `ui` extra using:
`poetry install --extras "ui"`
