### ISSUE TITLE
Change chunking/splitting method from SentenceWindowNodeParser to SentenceSplitter or SemanticSplitterNodeParser

### ISSUE THREAD

**Issue by lenartgolob** [zylon-ai/private-gpt#1917]
I am getting very bad responses from the LLM when chatting with the file I uploaded. I am using Qdrant as a vector DB and I checked the contents in the database and realized that all the chunks are only one sentence long. 
This is because by default privategpt uses SentenceWindowNodeParser to split the text in `ingest_service.py`
`node_parser = SentenceWindowNodeParser.from_defaults()`

instead of the default I tried implementing SentenceSplitter like this:
`node_parser = SentenceSplitter.from_defaults(chunk_size=1024, chunk_overlap=200)`

I also tried implementing SemanticSplitterNodeParser like this:
```
        ollama_embedding = OllamaEmbedding(
            model_name="nomic-embed-text:latest",
            base_url="http://localhost:11434",
            ollama_additional_kwargs={"mirostat": 0},
        )           

        node_parser = SemanticSplitterNodeParser(buffer_size=5, embed_model=ollama_embedding)
```

Both implementations work and the embedding happens without errors, but when I check the database the file is still split by sentences instead of 1024 characters in case of SentenceSplitter or by meaning in case of SemanticSplitterNodeParser.

Should I make some other changes and what am I missing? Why is splitting by sentence the default if it's so ineffective?
I run privategpt with:
`PGPT_PROFILES=vllm make run
`
Thanks in advance for any help!

**Comment by AlexPerkin** [comment]
Try for example
`node_parser = SentenceWindowNodeParser.from_defaults(window_size=20)`

**Comment by sonaliverma** [comment]
No need to pass Sentence Splitter dynamically as it is by default present in Service Context Class definition.

Below is the configuration in Service Context.

node_parser = (
            text_splitter  # text splitter extends node parser
            or node_parser
            or _get_default_node_parser(
                chunk_size=chunk_size or DEFAULT_CHUNK_SIZE,
                chunk_overlap=chunk_overlap or SENTENCE_CHUNK_OVERLAP,
                callback_manager=callback_manager,
            )
        )

If you don't pass any splitting method in the transformations , it will go to _get_default_node_parser which is using SentenceSplitter. Follow below steps:

Go to ingest_service.py and in transformations remove node parser
transformations=[node_parser,embedding_component.embedding_model]

**Comment by jaluma** [comment]
Currently, by default, we use the sentence division as you have said. We have chosen this way because several articles have commented that it is the simplest but one of more effective way to do it. We will discuss whether it is still the best current way, or if not, choose another default chunking way. In any case, I invite you to give your feedback :)

**Comment by HardikJain02** [comment]
do you have any plan to implement better splitters?

**Comment by jaluma** [comment]
By default, I would say almost no. It is very difficult to find a general solution to solve all the problems. Anyway, we have on the roadmap to move to the semantic splitter, but we don't do a lot of experiments to find out how good it is
