### ISSUE TITLE
Logger doesn't log my custom log

### ISSUE THREAD

**Issue by lenartgolob** [zylon-ai/private-gpt#1918]
I am having issues changing the splitting method and I want to debug using the logs. I added some custom logs in `ingest_service.py` like this:
logger.info("SemanticSplitterNodeParser: =%s", dir(node_parser))

These are the default logs in this file which work:
```
    def ingest_file(self, file_name: str, file_data: Path) -> list[IngestedDoc]:
        logger.info("Ingesting file_name=%s", file_name)
        documents = self.ingest_component.ingest(file_name, file_data)
        logger.info("Finished ingestion file_name=%s", file_name)
        return [IngestedDoc.from_document(document) for document in documents]
```
Both this logs are execute when I embed a file. So I also tried adding a log like this:

```
    def ingest_file(self, file_name: str, file_data: Path) -> list[IngestedDoc]:
        logger.info("Ingesting file_name=%s", file_name)
        documents = self.ingest_component.ingest(file_name, file_data)
        logger.info("Finished ingestion file_name=%s", file_name)
        logger.info("LOG TEST=%s", file_name)
        return [IngestedDoc.from_document(document) for document in documents]
```
Even if I add a log like this it still won't be displayed, only the two default logs are displayed like this:
14:44:44.484 [INFO    ] private_gpt.server.ingest.ingest_service - Ingesting file_names=['file.pdf']
14:44:49.258 [INFO    ] private_gpt.server.ingest.ingest_service - Finished ingestion file_name=['file.pdf']

I run privategpt with: 
PGPT_PROFILES=vllm make run

Thanks for any help in advance!

**Comment by nikjohn7** [comment]
How did you sort this out?
