### ISSUE TITLE
Anyone has success at using this to analyse/query json data files

### ISSUE THREAD

**Issue by longmtran** [zylon-ai/private-gpt#1934]
Hi,

I'm a total beginner. I'm playing around with this tool and its UI. I have it all set up and running locally with Ollama. I can upload json files and the embeddings are created successfully. But when I ask logical question or query/analyse the json data, the model is having a hard time answering it. I tried llama3, mistral. Questions like: get me the object where "x" attribute is "a", and "y" attribute is "b". It cant answer it.

Is this sort of task outside the scope of this and this is more for text based document rather than data documents?

Thanks!

**Comment by jaluma** [comment]
You can check this library that allow to get Json based on a schema: https://github.com/noamgat/lm-format-enforcer
