### ISSUE TITLE
About Log Files

### ISSUE THREAD

**Issue by Siraj-Bhai** [zylon-ai/private-gpt#1936]
I work on this for several months. But now I need to check the log files of PGPT. Where can I find the Log Files ? or How to create the Log Files ?

**Comment by alxspiker** [comment]
Hi @Siraj-Bhai,

To find or create log files for PGPT, you can use the `ingest_folder.py` script, which includes logging functionality. Here’s how you can do it:

1. **Run the Script with Log File Argument**:
   You can specify a log file path using the `--log-file` argument when running the script. For example:
   ```sh
   python scripts/ingest_folder.py /path/to/folder --log-file /path/to/logfile.log
   ```

2. **Log Configuration**:
   The script sets up a `FileHandler` if the `--log-file` argument is provided. Logs will include timestamps, log levels, and messages.

3. **Example Usage**:
   ```sh
   python scripts/ingest_folder.py /data/documents --log-file /logs/pgpt_ingestion.log
   ```

This will create a `pgpt_ingestion.log` file in the specified directory, containing all log messages related to the ingestion process.

### Adding Logging to Other Scripts

If you need to add logging to other parts of the project, you can use Python's built-in logging module. Here’s an example of how to set it up:

1. **Import the Logging Module**:
   ```python
   import logging
   ```

2. **Configure Logging**:
   ```python
   logging.basicConfig(
       level=logging.INFO,
       format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
       handlers=[
           logging.FileHandler("pgpt.log"),
           logging.StreamHandler()
       ]
   )
   ```

3. **Add Logging Statements**:
   ```python
   logger = logging.getLogger(__name__)

   def some_function():
       logger.info("This is an info message")
       try:
           # Your code logic here
       except Exception as e:
           logger.error("An error occurred", exc_info=True)
   ```

This setup will create a `pgpt.log` file in the directory where you run your script, containing all log messages.

If you need further assistance or more detailed instructions, feel free to ask!

Best regards,
[alxspiker](https://github.com/alxspiker)
