### ISSUE TITLE
Llama CPP to make several simultaneous requests

### ISSUE THREAD

**Issue by rmansoul** [zylon-ai/private-gpt#1957]
Hi!
I'm using Llama CPP to make several simultaneous requests, but I'm having memory problems (out_of_memory). Is there a parameter in Llama CPP that allows me to manage these simultaneous requests and avoid this memory problem? If so, how can I use it effectively?
the memory problem consumes gpu memory ?

Thank you !

**Comment by jaluma** [comment]
Could you move to Ollama? Last version of Ollama has in-memory queue to support simultaneous request. If no, you will need to request changes in Llama-CPP to support them.
