### ISSUE TITLE
How to improve accuracy of answers?

### ISSUE THREAD

**Issue by mjung8** [zylon-ai/private-gpt#1964]
Looking for help in understanding how this works and what's going on.

I'm using the recommended Ollama configuration.

What did I do wrong that I'm getting these incorrect answers? Or what do I not understand about how PrivateGPT works and what it means about the 'provided context'?

Please see attached images.

Both Taco Bell and descriptions for the character Senna are on Page 2. As mentioned above, maybe I have the wrong idea of how this is supposed to work but these responses are not what I'm looking for.

![Screenshot 2024-06-07 at 01-46-30 My Private GPT](https://github.com/zylon-ai/private-gpt/assets/29390525/ac71f08e-f424-4fb4-8c3e-e4635e3b8a26)

This is from the source document.
![chapter 1](https://github.com/zylon-ai/private-gpt/assets/29390525/f4490da5-9365-40a3-85f1-0d06b120ee53)

I don't think this is the right approach but I looked in the database for what the data looks like and it's like this - using DB Browser for SQLite, exporting the .bin, using a converter.

![chapter 1 - 1](https://github.com/zylon-ai/private-gpt/assets/29390525/950d5bac-ce92-4202-97c9-d79f43be1ddf)

Thank you.

**Comment by HardikJain02** [comment]
Can you please point to the code for first three points?
