### ISSUE TITLE
Twitter Handle is incorrect in Readme

### ISSUE THREAD

**Issue by NishantPuri99** [zylon-ai/private-gpt#1971]
I'm completely new here and was browsing this repo.

In the Documentation, the Twitter Handle for Private GPT points to **https://twitter.com/PrivateGPT_AI**

This twitter handle **doesn't** exist
![image](https://github.com/zylon-ai/private-gpt/assets/45734004/091b4481-2ce1-4c1f-9bba-20271ea8fc5b)

Should it be: **https://twitter.com/ZylonPrivateGPT** instead?

If yes, can I go ahead and raise a PR for this documentation change?

**Comment by jaluma** [comment]
Good catch! Go ahead, waiting to merge :)
