### ISSUE TITLE
unable to run privateGPT.py

### ISSUE THREAD

**Issue by Harixy** [zylon-ai/private-gpt#1976]
/home/harix/.local/lib/python3.12/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing HuggingFaceEmbeddings from langchain.embeddings is deprecated. Please replace deprecated imports:

>> from langchain.embeddings import HuggingFaceEmbeddings

with new imports of:

>> from langchain_community.embeddings import HuggingFaceEmbeddings
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here https://python.langchain.com/v0.2/docs/versions/v0_2/ 
  warn_deprecated(
/home/harix/.local/lib/python3.12/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing Chroma from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import Chroma

with new imports of:

>> from langchain_community.vectorstores import Chroma
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here https://python.langchain.com/v0.2/docs/versions/v0_2/ 
  warn_deprecated(
/home/harix/.local/lib/python3.12/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import GPT4All`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/home/harix/.local/lib/python3.12/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import LlamaCpp`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/home/harix/.local/lib/python3.12/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 0.3.0. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFaceEmbeddings`.
  warn_deprecated(
/home/harix/.local/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Failed to load libllamamodel-mainline-cuda-avxonly.so: dlopen: libcuda.so.1: cannot open shared object file: No such file or directory
gguf_init_from_file: invalid magic characters 'lmgg'
gguf_init_from_file: invalid magic characters 'lmgg'
load_gguf: gguf_init_from_file failed
Traceback (most recent call last):
  File "/home/harix/Downloads/imartinez-privateGPT-main/privateGPT.py", line 87, in <module>
    main()
  File "/home/harix/Downloads/imartinez-privateGPT-main/privateGPT.py", line 42, in main
    llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harix/.local/lib/python3.12/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harix/.local/lib/python3.12/site-packages/pydantic/v1/main.py", line 1100, in validate_model
    values = validator(cls_, values)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harix/.local/lib/python3.12/site-packages/langchain_community/llms/gpt4all.py", line 145, in validate_environment
    values["client"] = GPT4AllModel(
                       ^^^^^^^^^^^^^
  File "/home/harix/.local/lib/python3.12/site-packages/gpt4all/gpt4all.py", line 236, in __init__
    self.model = LLModel(self.config["path"], n_ctx, ngl, backend)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harix/.local/lib/python3.12/site-packages/gpt4all/_pyllmodel.py", line 251, in __init__
    raise RuntimeError(f"Unable to instantiate model: {errmsg}")
RuntimeError: Unable to instantiate model: Unsupported file format

**Comment by jaluma** [comment]
Currently, we don't use `langchain` or `GPT4All` anymore.

Can you fetch last changes? We moved the repo url to `git remote set-url origin git@github.com:zylon-ai/private-gpt.git`, please update code source and tell us :)

Source: https://discord.com/channels/1164200432894234644/1164200970180374528/1219981275364855818
