### ISSUE TITLE
Best Way to Run as a Service?

### ISSUE THREAD

**Issue by DennisFaucher** [zylon-ai/private-gpt#1978]
Hi. Great software. Working great with my local install of ollama.
Is there a way to run "PGPT_PROFILES=ollama make run" in the background or as a service? I tried "nohup command &" but that failed. TIA.

**Comment by Pierrelouis2** [comment]
Hello, did you try running it like this it worked for me : `PGPT_PROFILES=ollama nohup make run &`

**Comment by DennisFaucher** [comment]
Oh. Interesting. I will try that. Thank you.

**Comment by Pierrelouis2** [comment]
If you want i also just made it so you can run it as a unix service : 

```private-gpt.service
[Unit]
Description=private GPT
After=network.target

[Service]
WorkingDirectory=/path/to/privategpt/directory
ExecStart=/bin/bash -c 'cd /path/to/privategpt/directory && PGPT_PROFILES=ollama make run' #maybe the cd is not necessary
Environment=PGPT_PROFILES=ollama
Restart=on-failure
User=yourusername

[Install]
WantedBy=multi-user.target
```
Then `sudo systemctl daemon-reload` and `sudo systemctl start private-gpt.service`

**Comment by DennisFaucher** [comment]
That's beautiful

**Comment by DennisFaucher** [comment]
The nohup command worked perfectly. Thank you.
