### ISSUE TITLE
LLM change

### ISSUE THREAD

**Issue by dejankocic** [zylon-ai/private-gpt#1981]
Hello,

Could you please point me to instructions how to change LLM?

Thx,
D.

**Comment by dejankocic** [comment]
any advise?

**Comment by jaluma** [comment]
Since our recommendation is to use Ollama, I am attaching our documentation where there is an explanation on how to change the LLM:
https://docs.privategpt.dev/manual/advanced-setup/llm-backends#using-ollama

Model names can find [here](https://ollama.com/library).
