### ISSUE TITLE
error when running setup.py

### ISSUE THREAD

**Issue by Caiden-P** [zylon-ai/private-gpt#1985]
```
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2.
401 Client Error. (Request ID: Root=1-66867938-63a777574abdc5a517fda5e0;15ff67d1-750c-4a78-854c-a4ab08dbe598)

Cannot access gated repo for url https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json.
Access to model mistralai/Mistral-7B-Instruct-v0.2 is restricted. You must be authenticated to access it.
```

**Comment by emorfaq** [comment]
Create a token on [huggingface](https://huggingface.co/) in the Setting>>Access Tokens 

Also  search and you need to agree to use the model you intend to use

![image](https://github.com/zylon-ai/private-gpt/assets/43461791/40763877-dad1-4459-889d-7f98b1db8de7)


pip install huggingface_hub
huggingface-cli login 

Provide the created token to login and continue to run setup..

**Comment by Caiden-P** [comment]
thanks, was following old docs on accident before auth was needed
