### ISSUE TITLE
Need to query multiple files.

### ISSUE THREAD

**Issue by Siraj-Bhai** [zylon-ai/private-gpt#1988]
Now, I'm ingesting multiple files and query something according to the file4. But the response is "The information is not provided in the give context". It happens because it reads only the first file. When I select the file4 then it gives the correct response.

For me, I need the corresponding response for all the files without selecting them.

**Comment by jaluma** [comment]
In the UI, there are two modes that allow you to query all files or only the selected file. Make sure it says: `All files`.
![image](https://github.com/zylon-ai/private-gpt/assets/414920/8d6c6590-94b6-45d7-ba8b-e6aee91ffcd0)

**Comment by Siraj-Bhai** [comment]
> In the UI, there are two modes that allow you to query all files or only the selected file. Make sure it says: `All files`. ![image](https://private-user-images.githubusercontent.com/414920/346535131-8d6c6590-94b6-45d7-ba8b-e6aee91ffcd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDE3MzksIm5iZiI6MTcyMDQ0MTQzOSwicGF0aCI6Ii80MTQ5MjAvMzQ2NTM1MTMxLThkNmM2NTkwLTk0YjYtNDVkNy1iYThiLWU2YWVlOTFmZmNkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMjIzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmI3ODI5ODkxMjgzZWJhMDgzZWMyZjVhMjVlODVkNDIxMjUxOGU5OWQwMjVhNGRhMWRkYjgwNjAzNWUyNTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iUOkHNe5CbGwEKGjmtHmmje5_IXi7tg1e5UHS-N8l3I)

Thank You for your kind response.

**Comment by ramsakal** [comment]
Is there way in api to selected multiple document and query
