### ISSUE TITLE
PrivateGPT user specific

### ISSUE THREAD

**Issue by mygitimage** [zylon-ai/private-gpt#1991]
hi there !! can you please guide me how to make this app user specific. so that each user can have access to their own data set

**Comment by jaluma** [comment]
Do you mean how to make a domain specific (e.g. healthcare, finance, etc.)? Right now, the only way to do this is by ingesting domain-specific files (knowledge) or by using a fine-tuned model trained on domain data. Anyway, any of these solution are agnostic to PrivateGPT :)

**Comment by mygitimage** [comment]
> Do you mean how to make a domain specific (e.g. healthcare, finance, etc.)? Right now, the only way to do this is by ingesting domain-specific files (knowledge) or by using a fine-tuned model trained on domain data. Anyway, any of these solution are agnostic to PrivateGPT :)

NO i mean that more than one user can access this app on local network and have access to their own data. like user can login and can query to their own uploaded document.

**Comment by jaluma** [comment]
OK, anyway we don't have any way to split data. If you want to do, you can define a custom metadata saving user information and filter using `context_filter` parameter.
