### ISSUE TITLE
change embedding BAAI/bge-small-en-v1.5 to something else

### ISSUE THREAD

**Issue by Tolkete** [zylon-ai/private-gpt#1992]
Dear all,
I'd like to change embedding BAAI/bge-small-en-v1.5 to danielheinz/e5-base-sts-en-de but it didn't work.
I change the settings.ymal to:
embedding:
  # Should be matching the value above in most cases
  mode: huggingface
  ingest_mode: simple
  embed_dim: 768 # 768 is for danielheinz/e5-base-sts-en-de

huggingface:
  embedding_hf_model_name: danielheinz/e5-base-sts-en-de
  access_token: ${HUGGINGFACE_TOKEN:}

After running: poetry run python scripts/setup
$ poetry run python scripts/setup
09:41:07.326 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
Downloading embedding BAAI/bge-small-en-v1.5
Fetching 14 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 6987.18it/s]
Embedding model downloaded!

Any idea? Why is the wrong embedding downloaded, where can I fix this?
Thanks for your help.
Regards, MIchael

**Comment by jaluma** [comment]
Are there any exceptions or other logs?
FYI: If you decide to change the embedding model, you will have to wipe data. You can do using `make wipe`

**Comment by Tolkete** [comment]
No, there are any exceptions. I just saw that the wrong model was loaded. 
The dimension of BAAI/bge-small-en-v1.5 is 384 and for danielheinz/e5-base-sts-en-de is 768 by running ingest I saw an error due to the wrong dimension. This was the point to look deeper into this.

**Comment by jaluma** [comment]
And, now, is it working? Or continue doing nothing?

**Comment by Tolkete** [comment]
It's not working for danielheinz/e5-base-sts-en-de. I have no idea where to look into, therefore I open this threat.

**Comment by jaluma** [comment]
OK, let's check what step you did. If I understand correctly, you did:
1. Modify `huggingface.embedding_hf_model_name` to `danielheinz/e5-base-sts-en-de` in `settings.yml`.
2. Modify `embed_dim` to `embed_dim` to 768.
3. Run `poetry run python scripts/setup`.

I have seen a couple of things that could be:
* You are calling `scripts/setup` instead of run. I recommend you call `make run`.
* Remember that it is better to define `PGPT_PROFILES` with the profile selected. So, as I would do, define your model in `settings-local.yml`, and run using `PGPT_PROFILES=local make run`. This will download and run PrivateGPT with your model.

I've just tested the embedding model, and it's running successfully on my machine.

**Comment by Tolkete** [comment]
Dear Jaluma, 
Thanks the model is loaded. 
Sorry, I did not formulate my question precisely. If I run "make ingest source_documents" BAAI/bge-small-en-v1.5 was loaded instead of  danielheinz/e5-base-sts-en-de.
private_gpt.components.embedding.embedding_component - Initializing the embedding model in mode=huggingface
18:00:36.271 [INFO    ] sentence_transformers.SentenceTransformer - Load pretrained SentenceTransformer: BAAI/bge-small-en-v1.5
18:00:38.057 [INFO    ] sentence_transformers.SentenceTransformer - 2 prompts are loaded, with the keys: ['query', 'text']
18:00:38.351 [INFO    ] llama_index.core.indices.loading - Loading all indices.

Is there a special settings.yaml for ingest? I thought it was done via settings.yaml.
Thanks for your time.
Regards, Michael

**Comment by Tolkete** [comment]
Addition: if bge-small-en-v1.5 is used for ingest and e5-base-sts-en-de for privatGPT than there is an dimension error.

**Comment by jaluma** [comment]
I attach you my changes. It's running as expected on my machine:
```

diff --git a/settings-local.yaml b/settings-local.yaml
index 48eeb0e..bc9b849 100644
--- a/settings-local.yaml
+++ b/settings-local.yaml
@@ -18,7 +18,7 @@ embedding:
   mode: huggingface
 
 huggingface:
-  embedding_hf_model_name: BAAI/bge-small-en-v1.5
+  embedding_hf_model_name: danielheinz/e5-base-sts-en-de
 
 vectorstore:
   database: qdrant
diff --git a/settings.yaml b/settings.yaml
index 8d882f7..f7dd75a 100644
--- a/settings.yaml
+++ b/settings.yaml
@@ -72,10 +72,10 @@ embedding:
   # Should be matching the value above in most cases
   mode: huggingface
   ingest_mode: simple
-  embed_dim: 384 # 384 is for BAAI/bge-small-en-v1.5
+  embed_dim: 768 # 384 is for BAAI/bge-small-en-v1.5
 
 huggingface:
-  embedding_hf_model_name: BAAI/bge-small-en-v1.5
+  embedding_hf_model_name: danielheinz/e5-base-sts-en-de
   access_token: ${HUGGINGFACE_TOKEN:}
 
 vectorstore:

```

With respect to the dimensionality error is normal if the vectors that are generated have different dimension.

**Comment by Tolkete** [comment]
Thanks I have a solution:
PGPT_PROFILES=michael make ingest source_documents
I just load my settings "michael" and ingest is using the right model. 
I'm not really familiar with the syntax of privateGPT yet, I still have to learn a lot. Thanks for your time.
Regards, Michael
