### ISSUE TITLE
How to use PGPT with LLM and Embeddings as OPENAI.

### ISSUE THREAD

**Issue by Siraj-Bhai** [zylon-ai/private-gpt#1994]
I need to switch the LLM and Embeddings to OPENAI from Mistralai and Huggingface.
And I already have the OpenAI API key.
Please guide me to success in this progress ?

**Comment by jaluma** [comment]
Please check the OpenAI documentation:
https://docs.privategpt.dev/manual/advanced-setup/llm-backends#using-openai
