### ISSUE TITLE
Chat via API

### ISSUE THREAD

**Issue by Siraj-Bhai** [zylon-ai/private-gpt#1995]
How to run PGPT via API with "/chat" endpoint ?

**Comment by jaluma** [comment]
PGPT follows OpenAI schema. Please check documentation: https://docs.privategpt.dev/api-reference/api-reference/contextual-completions/chat-completion

**Comment by GPTLocalhost** [comment]
> PGPT follows OpenAI schema. Please check documentation: https://docs.privategpt.dev/api-reference/api-reference/contextual-completions/chat-completion

What is the port for the endpoint?
