### ISSUE TITLE
Issue while installation

### ISSUE THREAD

**Issue by ashunaveed** [zylon-ai/private-gpt#2005]
### Pre-check

- [X] I have searched the existing issues and none cover this bug.

### Description

While i try to install, i am getting following error: 
(gpt) C:\Users\genco\OneDrive\Desktop\private-gpt-main>pip install build
Collecting build
  Downloading build-1.2.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: packaging>=19.1 in c:\programdata\anaconda3\envs\gpt\lib\site-packages (from build) (23.2)
Collecting pyproject_hooks (from build)
  Downloading pyproject_hooks-1.1.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: colorama in c:\programdata\anaconda3\envs\gpt\lib\site-packages (from build) (0.4.6)
Downloading build-1.2.1-py3-none-any.whl (21 kB)
Downloading pyproject_hooks-1.1.0-py3-none-any.whl (9.2 kB)
Installing collected packages: pyproject_hooks, build
Successfully installed build-1.2.1 pyproject_hooks-1.1.0

(gpt) C:\Users\genco\OneDrive\Desktop\private-gpt-main>poetry install --extras "ui llms-ollama embeddings-ollama vector-stores-qdrant"
Installing dependencies from lock file

Package operations: 15 installs, 0 updates, 2 removals

  - Removing build (1.0.3)
  - Removing pyproject-hooks (1.0.0)
  - Installing ffmpy (0.3.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  C:\ProgramData\anaconda3\envs\gpt\python.exe: can't open file 'C:\\ProgramData\\anaconda3\\envs\\gpt\\Lib\\site-packages\\pyproject_hooks\\_in_process\\_in_process.py': [Errno 2] No such file or directory

  at C:\ProgramData\anaconda3\envs\gpt\Lib\site-packages\poetry\installation\chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with ffmpy (0.3.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "ffmpy (==0.3.1)"'.

### Steps to Reproduce

simply followed the guidelines.

### Expected Behavior

complete installation

### Actual Behavior

failed installation.

### Environment

windows 11 with nvidia rtx 4060 with ollama.

### Setup Checklist

- [X] Confirm that you have followed the installation instructions in the project’s documentation.
- [X] Check that you are using the latest version of the project.
- [X] Verify disk space availability for model storage and data processing.
- [X] Ensure that you have the necessary permissions to run the project.

### NVIDIA GPU Setup Checklist

- [X] Check that the all CUDA dependencies are installed and are compatible with your GPU (refer to [CUDA's documentation](https://docs.nvidia.com/deploy/cuda-compatibility/#frequently-asked-questions))
- [X] Ensure an NVIDIA GPU is installed and recognized by the system (run `nvidia-smi` to verify).
- [X] Ensure proper permissions are set for accessing GPU resources.
- [ ] Docker users - Verify that the NVIDIA Container Toolkit is configured correctly (e.g. run `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`)

**Comment by jaluma** [comment]
Can you try to install using this guide?
```
python3.11 -m venv .venv
source .venv/bin/activate
pip install poetry
poetry install --extras "ui llms-ollama embeddings-ollama vector-stores-qdrant"
```

**Comment by stephendwolff** [comment]
I got exactly the same error on macos using the python3.11 venv poetry install commands you list. 

```
  - Installing ffmpy (0.3.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  /var/folders/1g/pdzxzrjs4ljbbqlz2k6kb82w0000gn/T/tmp5yp59e35/.venv/bin/python: can't open file '/Users/stephen/Documents/Development/HawkingHealth/private-gpt/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py': [Errno 2] No such file or directory
  

  at venv/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with ffmpy (0.3.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "ffmpy (==0.3.1)"'.
```

**Comment by stephendwolff** [comment]
I can see it's already an issue here

 - https://github.com/zylon-ai/private-gpt/issues/1378

but has been marked stale. I'll try installing ffmpy with pip before running the poetry command

**Comment by stephendwolff** [comment]
ok - so i had success - but also had to remove ffmpy and docx2txt from the `poetry.lock` file. 

Then i set up my venv, activated it and pip installed poetry, ffmpy and docx2txt.

```
$ pyenv local 3.11
$ python -m venv venv
$ source venv/bin/activate
(venv) $ pip install poetry ffmpy docx2txt 
(venv) $ poetry install --extras "ui llms-ollama embeddings-ollama vector-stores-qdrant"
```

**Comment by Siraj-Bhai** [comment]
> ### Pre-check
> * [x]  I have searched the existing issues and none cover this bug.
> 
> ### Description
> While i try to install, i am getting following error: (gpt) C:\Users\genco\OneDrive\Desktop\private-gpt-main>pip install build Collecting build Downloading build-1.2.1-py3-none-any.whl.metadata (4.3 kB) Requirement already satisfied: packaging>=19.1 in c:\programdata\anaconda3\envs\gpt\lib\site-packages (from build) (23.2) Collecting pyproject_hooks (from build) Downloading pyproject_hooks-1.1.0-py3-none-any.whl.metadata (1.3 kB) Requirement already satisfied: colorama in c:\programdata\anaconda3\envs\gpt\lib\site-packages (from build) (0.4.6) Downloading build-1.2.1-py3-none-any.whl (21 kB) Downloading pyproject_hooks-1.1.0-py3-none-any.whl (9.2 kB) Installing collected packages: pyproject_hooks, build Successfully installed build-1.2.1 pyproject_hooks-1.1.0
> 
> (gpt) C:\Users\genco\OneDrive\Desktop\private-gpt-main>poetry install --extras "ui llms-ollama embeddings-ollama vector-stores-qdrant" Installing dependencies from lock file
> 
> Package operations: 15 installs, 0 updates, 2 removals
> 
> * Removing build (1.0.3)
> * Removing pyproject-hooks (1.0.0)
> * Installing ffmpy (0.3.1): Failed
> 
> ChefBuildError
> 
> Backend subprocess exited when trying to invoke get_requires_for_build_wheel
> 
> C:\ProgramData\anaconda3\envs\gpt\python.exe: can't open file 'C:\ProgramData\anaconda3\envs\gpt\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py': [Errno 2] No such file or directory
> 
> at C:\ProgramData\anaconda3\envs\gpt\Lib\site-packages\poetry\installation\chef.py:164 in _prepare 160│ 161│ error = ChefBuildError("\n\n".join(message_parts)) 162│ 163│ if error is not None: → 164│ raise error from None 165│ 166│ return path 167│ 168│ def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
> 
> Note: This error originates from the build backend, and is likely not a problem with poetry but with ffmpy (0.3.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "ffmpy (==0.3.1)"'.
> 
> ### Steps to Reproduce
> simply followed the guidelines.
> 
> ### Expected Behavior
> complete installation
> 
> ### Actual Behavior
> failed installation.
> 
> ### Environment
> windows 11 with nvidia rtx 4060 with ollama.
> 
> ### Additional Information
> _No response_
> 
> ### Version
> _No response_
> 
> ### Setup Checklist
> * [x]  Confirm that you have followed the installation instructions in the project’s documentation.
> * [x]  Check that you are using the latest version of the project.
> * [x]  Verify disk space availability for model storage and data processing.
> * [x]  Ensure that you have the necessary permissions to run the project.
> 
> ### NVIDIA GPU Setup Checklist
> * [x]  Check that the all CUDA dependencies are installed and are compatible with your GPU (refer to [CUDA's documentation](https://docs.nvidia.com/deploy/cuda-compatibility/#frequently-asked-questions))
> * [x]  Ensure an NVIDIA GPU is installed and recognized by the system (run `nvidia-smi` to verify).
> * [x]  Ensure proper permissions are set for accessing GPU resources.
> * [ ]  Docker users - Verify that the NVIDIA Container Toolkit is configured correctly (e.g. run `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`)

Yeah I'm also faced this issue but I soved this.
What to do is,
``pip install build``
``poetry add build``
poetry lock``
and try ``poetry install --extras "ui llms-ollama embeddings-ollama vector-stores-qdrant"``

**Comment by Siraj-Bhai** [comment]
Yeah I'm also faced this issue but I soved this.
What to do is,
``pip install build``
``poetry add build``
``poetry lock``
and try ``poetry install --extras "ui llms-ollama embeddings-ollama vector-stores-qdrant"``

**Comment by jaluma** [comment]
Can you try with last changes?

**Comment by Siraj-Bhai** [comment]
> Can you try with last changes?

Yeah

**Comment by Castolus** [comment]
> Can you try with last changes?

I´ve tried and have the same error. I had PGPT allready installed, but pulled latest updates regarding Llama 3 as default, and new version of pyprject.toml. Then i poetry update and poetry locked, and installed dependencies to run it fully local. I got the error during this last installation.

**Comment by jaluma** [comment]
What version of `ffmpy` is it installing? It should be using a git repository as a base and uploading your installed version to 0.3.2.

**Comment by Castolus** [comment]
> What version of `ffmpy` is it installing? It should be using a git repository as a base and uploading your installed version to 0.3.2.

- Downgrading ffmpy (0.3.3 333a19e -> 0.3.2 333a19e)

**Comment by jaluma** [comment]
Can you try to remove `venv` and recreate it? You shouldn't have a newest version.

**Comment by Castolus** [comment]
Yo mean removing .venv folder and then run this?:

python3.11 -m venv .venv
source .venv/bin/activate
pip install poetry
poetry install --extras "ui llms-llama-cpp embeddings-huggingface vector-stores-qdrant rerank-sentence-transformers"

**Comment by Castolus** [comment]
> source .venv/bin/activate

I don´t have any ".venv" folder since i created the environment directlly on IntelliJ.
