### ISSUE TITLE
[QUESTION] Request, can we have docker installation documentation?

### ISSUE THREAD

**Issue by salimfadhley** [zylon-ai/private-gpt#2015]
### Question

It looks like the project is docker-ready, but one cannot simply "docker-compose up" this project. Can you provide some documentation as to how a user can correctly get a dockerized version of this project up and running?

**Comment by jaluma** [comment]
We are making changes to improve the Docker experience. In a few days it should be available in the documentation.

**Comment by salimfadhley** [comment]
That would be amazing. Could you consider supporting a docker-compose config that "just runs", so you can run the project without access to source code using only official published images? That would help people run the software on appliance-type servers.

**Comment by jaluma** [comment]
Yep sure. I will come back here when we have the solution ready :)

**Comment by Bowenf3** [comment]
bump :)

**Comment by jaluma** [comment]
@salimfadhley @Bowenf3 I forgot to ping this issue.
We've already done, using docker-compose profiles :)
https://docs.privategpt.dev/quickstart/getting-started/quickstart

**Comment by salimfadhley** [comment]
thank you!
