### ISSUE TITLE
[QUESTION] Support for Llama on Azure AI Studio

### ISSUE THREAD

**Issue by aulkiller** [zylon-ai/private-gpt#2050]
### Question

Is there any possibility to support llama from azure ai studio? Since llama from Ollama and Llamacpp is working

**Comment by jaluma** [comment]
What is it the problem? You should enable `azopenai` profile and update `azopenai.llm_model` setting

**Comment by aulkiller** [comment]
So what should be the mode? azopenai?

Because when using azopenai i got this

![image](https://github.com/user-attachments/assets/6c716338-c3f8-4e73-b73e-fc00f75713bb)

![image](https://github.com/user-attachments/assets/1f71e013-07de-435c-a72c-d37cfbb500ac)

The config is something like this

![image](https://github.com/user-attachments/assets/d995e945-c504-4bbf-b8d0-0e4824be08e0)

**Comment by aulkiller** [comment]
@jaluma your input will be kindly appreciated. Also i wonder why closing the question so soon?

**Comment by aulkiller** [comment]
Nevermind i got it to work with vllms instead of azopenai alone

![image](https://github.com/user-attachments/assets/5c237138-e475-477c-936d-9f5d465344d2)
