### ISSUE TITLE
[QUESTION] When I ingest a file, the following error was reported. Has anyone encountered a similar problem?

### ISSUE THREAD

**Issue by cuteyang** [zylon-ai/private-gpt#2100]
### Question

I tried PGPT_PROFILES=local or PGPT_PROFILES=mock mode, but the problem is the same.
The following is the error message：

16:54:58.949 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'mock']
16:55:27.470 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=mock
16:55:31.156 [INFO    ] private_gpt.components.embedding.embedding_component - Initializing the embedding model in mode=huggingface
16:55:33.483 [INFO    ] sentence_transformers.SentenceTransformer - Load pretrained SentenceTransformer: nomic-ai/nomic-embed-text-v1.5
16:55:55.432 [WARNING ] transformers_modules.nomic-ai.nomic-bert-2048.c1b1fd7a715b8eb2e232d34593154ac782c98ac9.modeling_hf_nomic_bert - <All keys matched successfully>
16:55:57.389 [INFO    ] sentence_transformers.SentenceTransformer - 2 prompts are loaded, with the keys: ['query', 'text']
16:55:57.398 [INFO    ] llama_index.core.indices.loading - Loading all indices.
16:55:57.411 [INFO    ]                  __main__ - Ingesting files=['cf.txt']
16:55:57.413 [INFO    ] private_gpt.server.ingest.ingest_service - Ingesting file_names=['cf.txt']
Traceback (most recent call last):
  File "/home/ycq/GPT/private-gpt/scripts/ingest_folder.py", line 123, in <module>
    worker.ingest_folder(root_path, args.ignored)
  File "/home/ycq/GPT/private-gpt/scripts/ingest_folder.py", line 59, in ingest_folder
    self._ingest_all(self._files_under_root_folder)
  File "/home/ycq/GPT/private-gpt/scripts/ingest_folder.py", line 63, in _ingest_all
    self.ingest_service.bulk_ingest([(str(p.name), p) for p in files_to_ingest])
  File "/home/ycq/GPT/private-gpt/private_gpt/server/ingest/ingest_service.py", line 87, in bulk_ingest
    documents = self.ingest_component.bulk_ingest(files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ycq/GPT/private-gpt/private_gpt/components/ingest/ingest_component.py", line 135, in bulk_ingest
    saved_documents.extend(self._save_docs(documents))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ycq/GPT/private-gpt/private_gpt/components/ingest/ingest_component.py", line 142, in _save_docs
    self._index.insert(document, show_progress=True)
  File "/root/.cache/pypoetry/virtualenvs/private-gpt-WF-kgMXv-py3.11/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 209, in insert
    nodes = run_transformations(
            ^^^^^^^^^^^^^^^^^^^^
TypeError: llama_index.core.ingestion.pipeline.run_transformations() got multiple values for keyword argument 'show_progress'

**Comment by pierreali-gerp** [comment]
I'm getting the same error when uploading a .pptx file (after installing the suggested dependencies: torch, transformers, python-pptx, and pillow). Does anyone know how to solve this issue?

**Comment by pierreali-gerp** [comment]
> I'm getting the same error when uploading a .pptx file (after installing the suggested dependencies: torch, transformers, python-pptx, and pillow). Does anyone know how to solve this issue?

I might have found the problem. To install the dependencies needed to read .pptx files, I was forced to recreate the "poetry.lock" file by running `poetry lock`. However, by doing so, I was also changing the versions of the locked dependencies. Running `poetry lock --no-update` instead of the previous one solved the issue in my case.

**Comment by jaluma** [comment]
Are you in the latest version? This was fixed in #2090

**Comment by yaziciali** [comment]
Yes, it is latest. 2092
