### ISSUE TITLE
[BUG] PrivateGPT only able to hold 2 files in its context?

### ISSUE THREAD

**Issue by gupp41** [zylon-ai/private-gpt#2102]
### Pre-check

- [X] I have searched the existing issues and none cover this bug.

### Description

I have installed PrivateGPT on my Mac using the following string:
`poetry install --extras "ui vector-stores-qdrant llms-ollama embeddings-ollama"`
running llama3.1
I have uploaded about 7 HTML files full of text hoping to run queries on them.  
With RAG mode selected and with all files unselected (so it should be using all of them) it only seems to be able to hold 2 files in its context window at a maximum.  I see this by the sources listed.
All other modes selected also could not use more than 2 files for context.

### Steps to Reproduce

Install PrivateGPT with standard params:
poetry install --extras "ui vector-stores-qdrant llms-ollama embeddings-ollama"
Try  to add more than two files via the GUI and run queries on them in RAG mode.

### Expected Behavior

Should be querying all files uploaded

### Actual Behavior

Only queries maximum 2 files

### Environment

iMac 2021 24", 16GB RAM, 256 SSD, MacOS Sonoma

### Setup Checklist

- [X] Confirm that you have followed the installation instructions in the project’s documentation.
- [X] Check that you are using the latest version of the project.
- [X] Verify disk space availability for model storage and data processing.
- [X] Ensure that you have the necessary permissions to run the project.

### NVIDIA GPU Setup Checklist

- [ ] Check that the all CUDA dependencies are installed and are compatible with your GPU (refer to [CUDA's documentation](https://docs.nvidia.com/deploy/cuda-compatibility/#frequently-asked-questions))
- [ ] Ensure an NVIDIA GPU is installed and recognized by the system (run `nvidia-smi` to verify).
- [ ] Ensure proper permissions are set for accessing GPU resources.
- [ ] Docker users - Verify that the NVIDIA Container Toolkit is configured correctly (e.g. run `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`)

**Comment by unfixa1** [comment]
This problem may be related to the limitation of the context window. It is recommended that the development team check the part of the code that handles the file context to ensure that it can support queries for multiple files.

In addition, you should use [Servbay](https://servbay.com) to check your development environment, which is better than Docker on Mac and can ensure that there is no compatibility conflict in the environment

**Comment by HardikJain02** [comment]
same issue, cant hold more than three pdfs. but in terminal it says it ingested the pdfs but neither its visible in ui nor ai replies with its context. [using openai llm and embeddings]

**Comment by HardikJain02** [comment]
I am sorry but my issue happen to be this https://github.com/zylon-ai/private-gpt/issues/1960 as there was no error so i got confused.
