### ISSUE TITLE
[QUESTION] cannot change settings when using docker compose

### ISSUE THREAD

**Issue by Just-enki** [zylon-ai/private-gpt#2103]
### Problem

Im using docker to set up a local Pgpt based chatbot. Im creating a docker container with `sudo docker compose --profile llamacpp-cpu up` as defined in docker-compose.yaml . This starts the container with the default settings which to my understanding should be overwritten by settings-local.yaml, logs below.

> private-gpt-private-gpt-llamacpp-cpu-1  | 10:25:27.459 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'local']

Ive changed values in both settings.yaml as well as settings-local.yaml and recreated the container using `sudo docker compose --profile llamacpp-cpu up --force-recreate`, i've also tried deleting the old container however the changes still do not carry over into the new container. I tried forcing the use of only settings.yaml by editing settings_loader.py but this also had no effect.

### Question
I've managed to change the settings by entering the container as root, editing the files inside and restarting the container, this is far from the preferable way of tweaking the GPT. As I am a fairly new docker user, is there something i'm missing? What is the correct way of tweaking/creating new profile?

**Comment by jaluma** [comment]
You can create a new `settings-X.yaml` file, with your custom configuration and mount inside the image. To do that, modify private-gpt, adding a new volume line pointing your settings file to the private_folder. After, you can modify `PGPT_PROFILES` environment to run this profile.

**Comment by Just-enki** [comment]
The issue ended up being on the docker side. Deleting the image, clearing docker builder cache with `docker builder prune` and recreating the image has fixed the issue.
