### ISSUE TITLE
Any way to change size and amount of embeddings?

### ISSUE THREAD

**Issue by colrobloxkid69420** [zylon-ai/private-gpt#544]
Right now each embedding is a maximum of 500 tokens and there are 4 embeds max. What if I want embeds to include less tokens but for the AI to use more of them?

**Comment by colrobloxkid69420** [comment]
Thanks

**Comment by colrobloxkid69420** [comment]
It seems the code has changed a lot. Is there any way now to change the amount of embeddings?

**Comment by clab60917** [comment]
> It seems the code has changed a lot. Is there any way now to change the amount of embeddings?

Also interested but this answer ! I need to analyse some logs into a JSON file. The file upload is okay, then I have the "Maximum number of input tokens"

**Comment by jaluma** [comment]
Right now chunks are generated using the per-sentence strategy. You can get more info here: https://docs.llamaindex.ai/en/v0.10.17/api/llama_index.core.node_parser.SentenceWindowNodeParser.html
